sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+?-?\w+?$/

env:
  global:
  - secure: rQD9W5dkxhsHr3Zw6eq+GECXw0Zz4ou6G+pYsS3sbXlx0ZV/rsnRf3upKIjFzeA7gKIjM38DUPW3LE2Ijjk7ufTDuFa5jkAzHk6werh9c8enb4yV6izdREm7ODgbGLkcVS8k042WBE1s5ZLAOsP2DhU44ZhQtk/nJjg9Wq30tX2l9AIf0yYAkniM0lXahPmdYhSz4QT0SH4Sz1QgxQId87kzO33svK2oOhwVazIhxdKw4Qw8d576RH1ePQl9Xd8jQnMLW/O6/qdwFAHkg1DdP78v79FJziNn6AKuQXoSOkWqCQeTLiITQaBEp6EL+nl/JRE3yAhp2ZITG3w+8JW/Hz6Uu0H/2MKHBH35dxbYcsodL39v4LFR74AjFOpF0aioddkWrTBEp+q/gofge5Q0+SdN62LYOaTWwaP23PYmmpbCCrkJpY5oAgtbLNf7i+BQIO6q15L/RtazHnnNpwWq/zFmEyLeT93mREcBFacwb/mCunxMVI1Uw8tL0eYaYWmQHJfU8s+gIzxYK8xluzUycOnw5JUdHMk65K5HrLwoVbXcKrKt9H0rKBi+6SW6FLwL2dmN1nLvhkHkgTmXYeWp95RvRuDVfbbIw0uN76N5W0aeDI0ga+HW8KVldmHTGada+TOtFNZGctaTTzikgvZCGK6w8EEO+PhDiLOuLv9Zf5w=
  - secure: dZZ85ep6iPy/sGV4LfhhXGy+/l8Ksf2bcQ/pxRmYW4v2Oq9k0pPPZl1t2MsUKu51sfmv52Qh1JxrUJIZ/fD2RYZ9ZUB9q9J8ThwgGCsjcYITFAyY6nAvk7joK3d/Mj8G1tv+73eXUjKZDy9fIQYFFot+y6WO+0X3vYBidggzQxUNV9Wq5uIABLct7ip/u4fpaXn0qc+qLodlyBSpvbkMbjt8YMygkZ9jXd90SELVX4fOFSL354o6fPmKCeLf9XFyA5zuJh+e6rKYXxnpS9HOtvpmkay40omVYjaNQ1nF3Naj0AajHqFAleOeJHfkFWyKlPSoUif8poohYDA99E+W5E9Q8fiHwI9z1iJuLAxbH7cRKJdFAAki8cO8ESytBTzPZvTE68RXLcdf8fvycy9i0OYenHF9sf7xtlrkKPNo0+Y2xuQb3+Bzl+YmMJVXwZvkfdb+CXcJVr9iIqQj2CIcJ7TC6LJsjFYg6j8s2lVZ+cuSvmGrDPjVPjRETOkiFPQ3kwm28pevPP17bsanfuiSGhHL6IE9+Pp2k3gvf30XMnnG8SykFzuDAXHVcmNpBXI3wCDKxSzdtmeUNfGZ9N4NCphtGheg5L7XyLXhPv+BK4+rUfcbLnP0zMOCFyTt5Yei8uV70xf2gfNpUivcJ430Y2H5Iln7pskKnKc/6kz/j8k=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: T566YRDtGzFwMQ3ij2tXmLSbB8bMvNrJiw4xIPAVdmED2PVFRGtxSLPByqN4lcoyeAZ8pCs1/G6T6OCzRJ1eMqXlUZaLblIZCxGSA93w8XATRFMjYgKXmnZmrTk6cLCXnHZAS2VPPMsyyuVRw3HcDwIeaoQvy2jpwN2XUIaHIS0XEWcXlx1wN+grGo7ChH+A2fRuoBfG3x6ca3bifnB2A/K1XECLhBSwIgYinhJn3RGWsjw2ux8jsa5Ki2oV5uBmw9oFvC23vi0Zgvme455U60Gw2sx539EwOrmSbjj/2a2l+UuuGOy2NMP4n0vLgebFJZ0mKqAQLH20JntVE+y7MrjFW49pSb82PTJk4S9MpruW2lwm1034epcBBdLQT438sRhzF8FaWZHrPqEYEBKtZ2eZx4szZYorFr+1nfagzvaUOInE99EPB/axLJrLRlujYP4T+i5VYMqCocjqHOVmoVu7Zssh0RKXFzkHCrwFtVNOLJgdm34ULHj7SVzvUOY5nwTVQ4h5OBuSlL7XJrpObss/+SfuJUyfWWHsQZzUDt/0OzePlrCKtJp035D5eKVVadJUN4SKF2nE2Pwu7Yv86fHuMyOpEyHJksAzFx0nF/68QNKGH+Bf1szhr90i4ChnybRxoBWQgGOBF4trRPw0HJAXkWnbgIFNzep9FUxI0TA=
